name: Deploy WordPress Multisite with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Apply Terraform Configuration
        run: |
          terraform apply -auto-approve || (echo "⚠️ Terraform failed! Rolling back..." && terraform destroy -auto-approve)
        env:
          TF_VAR_cloud_provider: "aws"
          TF_VAR_vm_name: "wordpress-server"
          TF_VAR_vm_size: "t3.medium"
          TF_VAR_region: "us-east-1"
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_github_repo: ${{ secrets.GITHUB_REPO }}

      - name: Save VM IP
        run: echo "VM_IP=$(terraform output -raw vm_ip)" >> $GITHUB_ENV

  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fix SSH Key Permissions
        run: chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ env.VM_IP }} << 'EOF'
            cd /home/ubuntu/clgi-wordpress
            git pull origin main
            docker-compose down || echo "⚠️ Docker failed! Rolling back..."
            docker-compose up -d --build
            docker exec -it wordpress bash wp-cli-init.sh
          EOF