name: Terraform Destroy Now

on:
  workflow_dispatch:

jobs:
  destroy_now:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: "us-west-2"

      # Terraform Cloud API token
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

      # AWS credentials for Terraform provider
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate Terraform CLI with Terraform Cloud
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
{
  "credentials": {
    "app.terraform.io": {
      "token": "${{ secrets.TFE_TOKEN }}"
    }
  }
}
EOF

      - name: Terraform Init (with Cloud Backend)
        run: terraform -chdir=deployments/aws init -input=false

      - name: Terraform Destroy (auto approve)
        run: terraform -chdir=deployments/aws destroy -auto-approve -input=false
